services:
  sophon-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: sophon
      POSTGRES_USER: sophon
      POSTGRES_DB: sophon
    ports:
      - "5432:5432"
    volumes:
      - sophon-db:/var/lib/postgresql/data
    networks:
      - sophon-network
  sophon-server:
    build:
      context: .
      dockerfile: sophon-server/Dockerfile
    volumes:
      - sophon-files:/sophon-server
    ports:
      - "8099:8099"
      - "4000:4000"
    environment:
      DATABASE_URL: "postgres://sophon:sophon@sophon-postgres:5432/sophon?sslmode=disable"
      GOENV: development
      LOCAL_MODE: 1
      PLANDEX_BASE_DIR: /sophon-server
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - sophon-network
    depends_on:
      - sophon-postgres
    command: [ "/bin/sh", "-c", "/scripts/wait-for-it.sh sophon-postgres:5432 -- ./sophon-server" ]

networks:
  sophon-network:
    driver: bridge

volumes:
  sophon-db:
  sophon-files: